/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagePostImageDecode } from "../../funcs/imagePostImageDecode.js";
import { PostImageDecodeRequest$zodSchema } from "../../models/postimagedecodeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostImageDecodeRequest$zodSchema,
};

export const tool$imagePostImageDecode: ToolDefinition<typeof args> = {
  name: "image-post-image-decode",
  description: `解码并缩放图片

在 RAM 和 Flash 极其有限的设备上解码图片是一项繁重的任务。这个接口专为 IoT 和嵌入式开发设计，将复杂的图像解码和缩放操作转移到云端，直接输出适用于单片机屏幕的二进制像素流。

## 功能概述
此接口提供了灵活的云端图像预处理能力，帮助硬件开发者跳过繁琐的图像处理逻辑：
- **直接推流渲染**：如果选择输出纯像素流（如 RGB565），单片机收到网络数据后无需解析文件头，可直接将其写入显存，实现极低内存占用的边下边播。
- **完美适配屏幕**：无需在设备端编写裁剪或补边代码。只需传入目标屏幕的物理分辨率，接口会自动完成等比缩放、居中补色或铺满裁剪，确保最终显示画面不变形。
- **精准内存分配**：在动态缩放图片的场景下，服务端会在 HTTP 响应头中提前注入 \`X-Image-Width\` 和 \`X-Image-Height\`，方便设备在读取真实的二进制数据前进行准确的内存分配。

## 使用须知
- **请求格式**：无论是上传本地文件还是传递图片链接，请求体都必须使用 \`multipart/form-data\` 编码格式。
- **网络资源获取**：当您选择传递图片链接时，服务端会自动尝试获取该资源。请确保您提供的图片链接是公网直接可访问的，且不需要任何形式的登录鉴权。`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await imagePostImageDecode(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
