/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imageGetAvatarGravatar } from "../../funcs/imageGetAvatarGravatar.js";
import { GetAvatarGravatarRequest$zodSchema } from "../../models/getavatargravatarop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAvatarGravatarRequest$zodSchema.optional(),
};

export const tool$imageGetAvatarGravatar: ToolDefinition<typeof args> = {
  name: "image-get-avatar-gravatar",
  description: `获取Gravatar头像

提供稳定、易用的头像获取能力，适合在网页或应用中直接展示头像。`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await imageGetAvatarGravatar(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
