/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { miscGetMiscHotboard } from "../../funcs/miscGetMiscHotboard.js";
import { GetMiscHotboardRequest$zodSchema } from "../../models/getmischotboardop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetMiscHotboardRequest$zodSchema,
};

export const tool$miscGetMiscHotboard: ToolDefinition<typeof args> = {
  name: "misc-get-misc-hotboard",
  description: `查询热榜

想快速跟上网络热点？这个接口让你一网打尽各大主流平台的实时热榜/热搜！

## 功能概述
你只需要指定一个平台类型，就能获取到该平台当前的热榜数据列表。每个热榜条目都包含标题、热度值和原始链接。非常适合用于制作信息聚合类应用或看板。

## 三种使用模式

### 默认模式
只传 \`type\` 参数，返回该平台当前的实时热榜。

### 时光机模式
传 \`type\` + \`time\` 参数，返回最接近指定时间的热榜快照。如果不可用或无数据，会返回空。

### 搜索模式
传 \`type\` + \`keyword\` + \`time_start\` + \`time_end\` 参数，在指定时间范围内搜索包含关键词的热榜条目。可选传 \`limit\` 限制返回数量。`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await miscGetMiscHotboard(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
