/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { postSensitiveWordQuickCheck } from "../../funcs/postSensitiveWordQuickCheck.js";
import { PostSensitiveWordQuickCheckRequest$zodSchema } from "../../models/postsensitivewordquickcheckop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostSensitiveWordQuickCheckRequest$zodSchema.describe(
    `包含待检测文本 'text' 的JSON对象`,
  ),
};

export const tool$postSensitiveWordQuickCheck: ToolDefinition<typeof args> = {
  name: "-post-sensitive-word-quick-check",
  description: `敏感词检测（快速）

在你的社区或应用中，需要过滤不适合展示的内容时，这个接口可以帮你快速完成检测。

## 功能概述

这个接口可以识别文本中的敏感词，并返回是否命中、命中词列表等结果，适合用于评论区、社区、论坛和内容发布场景。

### 主要特性

- **快速检测**：能够一次处理整段文本中的多个命中内容
- **简繁体支持**：支持简体中文、繁体中文和混合文本检测
- **结果直观**：返回清晰的检测结果，方便直接接入审核流程
- **响应稳定**：适合日常内容审核和批量检查场景

无论是论坛、社交平台还是评论系统，这个接口都能帮你快速构建内容审核功能。`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await postSensitiveWordQuickCheck(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
