/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { textPostTextMarkdownToHtml } from "../../funcs/textPostTextMarkdownToHtml.js";
import { PostTextMarkdownToHtmlRequest$zodSchema } from "../../models/posttextmarkdowntohtmlop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostTextMarkdownToHtmlRequest$zodSchema.describe(
    `请求体使用 \`application/json\`。\`text\` 必填；\`format\` 和 \`sanitize\` 可选。`,
  ),
};

export const tool$textPostTextMarkdownToHtml: ToolDefinition<typeof args> = {
  name: "text-post-text-markdown-to-html",
  description: `Markdown 转 HTML

直接调用这个接口，就可以把 Markdown 文本转换成带样式的 HTML，而且它不只适合程序里动态注入，也适合在开发阶段直接预览。

## 如何使用与预览
- **默认模式：返回 JSON 里的 HTML 片段**：不传 \`format\` 时，接口会返回 JSON。您只需要读取响应里的 \`data.html\`，再赋值给前端容器，例如 \`element.innerHTML = data.html\`、Vue 的 \`v-html\`，或者 React 里配合 \`dangerouslySetInnerHTML\` 使用。
- **预览模式：直接返回完整 HTML 网页**：如果您想在浏览器里直接打开结果，或者想把响应保存成一个独立的 \`.html\` 文件，请传 \`format="html"\`。这个模式下，接口会直接返回带 \`<!DOCTYPE html><html>...\` 的完整网页源码。

## 功能概述
- **自带精美排版，无需手写 CSS**：返回结果已经内置样式，标题、引用、表格、任务列表和代码块都可以直接显示。
- **支持丰富的排版元素**：除了标准 Markdown，这个接口也可以正确处理 GFM 常见语法，例如表格、任务列表和带语言标记的代码块。
- **安全处理用户内容**：默认开启安全模式，会自动过滤原始 HTML 里的风险脚本。如果内容来源绝对可信，并且您确实需要保留原始 HTML，可以把 \`sanitize\` 设为 \`false\`。`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await textPostTextMarkdownToHtml(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
