/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { textPostTextMarkdownToPdf } from "../../funcs/textPostTextMarkdownToPdf.js";
import { PostTextMarkdownToPdfRequest$zodSchema } from "../../models/posttextmarkdowntopdfop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostTextMarkdownToPdfRequest$zodSchema.describe(
    `请求体使用 \`application/json\`。\`text\` 必填，\`theme\` 和 \`paper_size\` 可选。`,
  ),
};

export const tool$textPostTextMarkdownToPdf: ToolDefinition<typeof args> = {
  name: "text-post-text-markdown-to-pdf",
  description: `Markdown 转 PDF

当您的业务系统需要提供“导出为 PDF”的功能时，无需在后端部署复杂的排版引擎，只需将 Markdown 文本发给这个接口，即可直接获取打印级的 PDF 文件。

## 功能概述
- **服务端直接生成**：接口直接返回 PDF 文件二进制流，前端无需任何处理即可触发下载，后端也能轻松存盘归档。
- **多种精美主题与纸张**：内置了 GitHub、暗黑等多种专业排版主题，并支持 A4、Letter 等标准纸张。只需简单配置，就能生成符合业务场景的专业文档。
- **公网图片也可以直接带入 PDF**：除了纯文本和标准 Markdown 语法，这个接口也可以处理 \`data URI\` 图片，或者公网可访问的 \`http\`、\`https\` 图片链接。服务端会先通过代理抓取图片，并在渲染前内联到文档里，同时带有超时控制。`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await textPostTextMarkdownToPdf(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
