/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Language = {
  code?: string | undefined;
  name?: string | undefined;
  native?: string | undefined;
};

export const Language$zodSchema: z.ZodType<Language> = z.object({
  code: z.string().optional(),
  name: z.string().optional(),
  native: z.string().optional(),
});

export type GetAiTranslateLanguagesStyle = {
  code?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
};

export const GetAiTranslateLanguagesStyle$zodSchema: z.ZodType<
  GetAiTranslateLanguagesStyle
> = z.object({
  code: z.string().optional(),
  description: z.string().optional(),
  name: z.string().optional(),
});

export type GetAiTranslateLanguagesContext = {
  code?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
};

export const GetAiTranslateLanguagesContext$zodSchema: z.ZodType<
  GetAiTranslateLanguagesContext
> = z.object({
  code: z.string().optional(),
  description: z.string().optional(),
  name: z.string().optional(),
});

export type GetAiTranslateLanguagesData = {
  languages?: Array<Language> | undefined;
  styles?: Array<GetAiTranslateLanguagesStyle> | undefined;
  contexts?: Array<GetAiTranslateLanguagesContext> | undefined;
};

export const GetAiTranslateLanguagesData$zodSchema: z.ZodType<
  GetAiTranslateLanguagesData
> = z.object({
  contexts: z.array(z.lazy(() => GetAiTranslateLanguagesContext$zodSchema))
    .optional(),
  languages: z.array(z.lazy(() => Language$zodSchema)).optional(),
  styles: z.array(z.lazy(() => GetAiTranslateLanguagesStyle$zodSchema))
    .optional(),
});

export type TypicalResponseTimeMs = {
  fast_mode?: number | undefined;
  normal_mode?: number | undefined;
};

export const TypicalResponseTimeMs$zodSchema: z.ZodType<TypicalResponseTimeMs> =
  z.object({
    fast_mode: z.int().optional(),
    normal_mode: z.int().optional(),
  });

export type GetAiTranslateLanguagesPerformance = {
  fast_mode_available?: boolean | undefined;
  batch_translation_available?: boolean | undefined;
  max_text_length?: number | undefined;
  max_batch_size?: number | undefined;
  typical_response_time_ms?: TypicalResponseTimeMs | undefined;
};

export const GetAiTranslateLanguagesPerformance$zodSchema: z.ZodType<
  GetAiTranslateLanguagesPerformance
> = z.object({
  batch_translation_available: z.boolean().optional(),
  fast_mode_available: z.boolean().optional(),
  max_batch_size: z.int().optional(),
  max_text_length: z.int().optional(),
  typical_response_time_ms: z.lazy(() => TypicalResponseTimeMs$zodSchema)
    .optional(),
});

/**
 * 成功获取AI翻译配置信息！
 */
export type GetAiTranslateLanguagesResponse = {
  message?: string | undefined;
  data?: GetAiTranslateLanguagesData | undefined;
  performance?: GetAiTranslateLanguagesPerformance | undefined;
};

export const GetAiTranslateLanguagesResponse$zodSchema: z.ZodType<
  GetAiTranslateLanguagesResponse
> = z.object({
  data: z.lazy(() => GetAiTranslateLanguagesData$zodSchema).optional(),
  message: z.string().optional(),
  performance: z.lazy(() => GetAiTranslateLanguagesPerformance$zodSchema)
    .optional(),
}).describe("成功获取AI翻译配置信息！");
