/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

/**
 * 暂时无法获取相关内容，请稍后重试。
 */
export type GetDailyNewsImageBadGatewayResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetDailyNewsImageBadGatewayResponseBody$zodSchema: z.ZodType<
  GetDailyNewsImageBadGatewayResponseBody
> = z.object({
  code: z.string().optional().describe("机器可读的错误代码。"),
  message: z.string().optional().describe("人类可读的错误描述信息。"),
}).describe("暂时无法获取相关内容，请稍后重试。");

/**
 * 服务器内部错误。暂时无法生成图片，请稍后重试。
 */
export type GetDailyNewsImageInternalServerErrorResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetDailyNewsImageInternalServerErrorResponseBody$zodSchema:
  z.ZodType<GetDailyNewsImageInternalServerErrorResponseBody> = z.object({
    code: z.string().optional().describe("机器可读的错误代码。"),
    message: z.string().optional().describe("人类可读的错误描述信息。"),
  }).describe("服务器内部错误。暂时无法生成图片，请稍后重试。");

export type GetDailyNewsImageResponse =
  | Uint8Array
  | string
  | GetDailyNewsImageInternalServerErrorResponseBody
  | GetDailyNewsImageBadGatewayResponseBody;

export const GetDailyNewsImageResponse$zodSchema: z.ZodType<
  GetDailyNewsImageResponse
> = z.union([
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.lazy(() => GetDailyNewsImageInternalServerErrorResponseBody$zodSchema),
  z.lazy(() => GetDailyNewsImageBadGatewayResponseBody$zodSchema),
]);
