/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

/**
 * 上游服务错误。我们在尝试从新闻源（如微博、知乎等）获取数据时失败了。这可能是因为上游服务暂时不可用或更改了接口。这个问题通常很快会解决，请稍后重试。
 */
export type GetDailyNewsImageBadGatewayResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetDailyNewsImageBadGatewayResponseBody$zodSchema: z.ZodType<
  GetDailyNewsImageBadGatewayResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe(
  "上游服务错误。我们在尝试从新闻源（如微博、知乎等）获取数据时失败了。这可能是因为上游服务暂时不可用或更改了接口。这个问题通常很快会解决，请稍后重试。",
);

/**
 * 服务器内部错误。这可能是我们的图片渲染服务遇到了临时故障。我们已经被自动通知，请稍后重试。
 */
export type GetDailyNewsImageInternalServerErrorResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetDailyNewsImageInternalServerErrorResponseBody$zodSchema:
  z.ZodType<GetDailyNewsImageInternalServerErrorResponseBody> = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }).describe(
    "服务器内部错误。这可能是我们的图片渲染服务遇到了临时故障。我们已经被自动通知，请稍后重试。",
  );

export type GetDailyNewsImageResponse =
  | Uint8Array
  | string
  | GetDailyNewsImageInternalServerErrorResponseBody
  | GetDailyNewsImageBadGatewayResponseBody;

export const GetDailyNewsImageResponse$zodSchema: z.ZodType<
  GetDailyNewsImageResponse
> = z.union([
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.lazy(() => GetDailyNewsImageInternalServerErrorResponseBody$zodSchema),
  z.lazy(() => GetDailyNewsImageBadGatewayResponseBody$zodSchema),
]);
