/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

/**
 * 上游服务错误。我们无法从必应官方API获取到图片，并且备用图片方案也失败了。请稍后重试。
 */
export type GetImageBingDailyResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const GetImageBingDailyResponseBody$zodSchema: z.ZodType<
  GetImageBingDailyResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe(
  "上游服务错误。我们无法从必应官方API获取到图片，并且备用图片方案也失败了。请稍后重试。",
);

export type GetImageBingDailyResponse =
  | Uint8Array
  | string
  | GetImageBingDailyResponseBody;

export const GetImageBingDailyResponse$zodSchema: z.ZodType<
  GetImageBingDailyResponse
> = z.union([
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.lazy(() => GetImageBingDailyResponseBody$zodSchema),
]);
