/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * 你想要查询的热榜平台。请从[支持的平台列表](#enum-list)中选择。
 */
export const GetMiscHotboardType = {
  Bilibili: "bilibili",
  Acfun: "acfun",
  Weibo: "weibo",
  Zhihu: "zhihu",
  ZhihuDaily: "zhihu-daily",
  Douyin: "douyin",
  Kuaishou: "kuaishou",
  DoubanMovie: "douban-movie",
  DoubanGroup: "douban-group",
  Tieba: "tieba",
  Hupu: "hupu",
  Ngabbs: "ngabbs",
  V2ex: "v2ex",
  FiftyTwopojie: "52pojie",
  Hostloc: "hostloc",
  Coolapk: "coolapk",
  Baidu: "baidu",
  Thepaper: "thepaper",
  Toutiao: "toutiao",
  QqNews: "qq-news",
  Sina: "sina",
  SinaNews: "sina-news",
  NeteaseNews: "netease-news",
  Huxiu: "huxiu",
  Ifanr: "ifanr",
  Sspai: "sspai",
  Ithome: "ithome",
  IthomeXijiayi: "ithome-xijiayi",
  Juejin: "juejin",
  Jianshu: "jianshu",
  Guokr: "guokr",
  ThirtySixkr: "36kr",
  FiftyOnecto: "51cto",
  Csdn: "csdn",
  Nodeseek: "nodeseek",
  Hellogithub: "hellogithub",
  Lol: "lol",
  Genshin: "genshin",
  Honkai: "honkai",
  Starrail: "starrail",
  NeteaseMusic: "netease-music",
  QqMusic: "qq-music",
  Weread: "weread",
  Weatheralarm: "weatheralarm",
  Earthquake: "earthquake",
  History: "history",
} as const;
/**
 * 你想要查询的热榜平台。请从[支持的平台列表](#enum-list)中选择。
 */
export type GetMiscHotboardType = ClosedEnum<typeof GetMiscHotboardType>;

export const GetMiscHotboardType$zodSchema = z.enum([
  "bilibili",
  "acfun",
  "weibo",
  "zhihu",
  "zhihu-daily",
  "douyin",
  "kuaishou",
  "douban-movie",
  "douban-group",
  "tieba",
  "hupu",
  "ngabbs",
  "v2ex",
  "52pojie",
  "hostloc",
  "coolapk",
  "baidu",
  "thepaper",
  "toutiao",
  "qq-news",
  "sina",
  "sina-news",
  "netease-news",
  "huxiu",
  "ifanr",
  "sspai",
  "ithome",
  "ithome-xijiayi",
  "juejin",
  "jianshu",
  "guokr",
  "36kr",
  "51cto",
  "csdn",
  "nodeseek",
  "hellogithub",
  "lol",
  "genshin",
  "honkai",
  "starrail",
  "netease-music",
  "qq-music",
  "weread",
  "weatheralarm",
  "earthquake",
  "history",
]).describe("你想要查询的热榜平台。请从[支持的平台列表](#enum-list)中选择。");

export type GetMiscHotboardRequest = {
  type: GetMiscHotboardType;
  time?: number | undefined;
  keyword?: string | undefined;
  time_start?: number | undefined;
  time_end?: number | undefined;
  limit?: number | undefined;
};

export const GetMiscHotboardRequest$zodSchema: z.ZodType<
  GetMiscHotboardRequest
> = z.object({
  keyword: z.string().describe(
    "搜索模式：搜索关键词，在历史热榜中搜索包含该关键词的条目。需配合 time_start 和 time_end 使用。",
  ).optional(),
  limit: z.int().describe("搜索模式下最大返回条数，默认 50，最大 200。")
    .optional(),
  time: z.int().describe(
    "时光机模式：毫秒时间戳，返回最接近该时间的热榜快照。不传则返回当前实时热榜。",
  ).optional(),
  time_end: z.int().describe("搜索模式必填：搜索结束时间戳（毫秒）。")
    .optional(),
  time_start: z.int().describe("搜索模式必填：搜索起始时间戳（毫秒）。")
    .optional(),
  type: GetMiscHotboardType$zodSchema.describe(
    "你想要查询的热榜平台。请从[支持的平台列表](#enum-list)中选择。",
  ),
});

export type GetMiscHotboardBadGatewayDetails = {};

export const GetMiscHotboardBadGatewayDetails$zodSchema: z.ZodType<
  GetMiscHotboardBadGatewayDetails
> = z.object({});

/**
 * 暂时无法获取相关数据，请稍后重试。
 */
export type GetMiscHotboardBadGatewayResponseBody = {
  code?: string | undefined;
  details?: GetMiscHotboardBadGatewayDetails | undefined;
  message?: string | undefined;
};

export const GetMiscHotboardBadGatewayResponseBody$zodSchema: z.ZodType<
  GetMiscHotboardBadGatewayResponseBody
> = z.object({
  code: z.string().optional(),
  details: z.lazy(() => GetMiscHotboardBadGatewayDetails$zodSchema).optional(),
  message: z.string().optional(),
}).describe("暂时无法获取相关数据，请稍后重试。");

export type GetMiscHotboardInternalServerErrorDetails = {};

export const GetMiscHotboardInternalServerErrorDetails$zodSchema: z.ZodType<
  GetMiscHotboardInternalServerErrorDetails
> = z.object({});

/**
 * 获取热榜失败。服务器在处理数据时发生内部错误。
 */
export type GetMiscHotboardInternalServerErrorResponseBody = {
  code?: string | undefined;
  details?: GetMiscHotboardInternalServerErrorDetails | undefined;
  message?: string | undefined;
};

export const GetMiscHotboardInternalServerErrorResponseBody$zodSchema:
  z.ZodType<GetMiscHotboardInternalServerErrorResponseBody> = z.object({
    code: z.string().optional(),
    details: z.lazy(() => GetMiscHotboardInternalServerErrorDetails$zodSchema)
      .optional(),
    message: z.string().optional(),
  }).describe("获取热榜失败。服务器在处理数据时发生内部错误。");

export type GetMiscHotboardBadRequestDetails = {};

export const GetMiscHotboardBadRequestDetails$zodSchema: z.ZodType<
  GetMiscHotboardBadRequestDetails
> = z.object({});

/**
 * 请求参数错误。你提供的 `type` 参数不是我们支持的平台类型，请检查拼写。
 */
export type GetMiscHotboardBadRequestResponseBody = {
  code?: string | undefined;
  details?: GetMiscHotboardBadRequestDetails | undefined;
  message?: string | undefined;
};

export const GetMiscHotboardBadRequestResponseBody$zodSchema: z.ZodType<
  GetMiscHotboardBadRequestResponseBody
> = z.object({
  code: z.string().optional(),
  details: z.lazy(() => GetMiscHotboardBadRequestDetails$zodSchema).optional(),
  message: z.string().optional(),
}).describe(
  "请求参数错误。你提供的 `type` 参数不是我们支持的平台类型，请检查拼写。",
);

export type GetMiscHotboardResult = {
  title?: string | undefined;
  hot_value?: string | undefined;
  url?: string | undefined;
};

export const GetMiscHotboardResult$zodSchema: z.ZodType<GetMiscHotboardResult> =
  z.object({
    hot_value: z.string().optional(),
    title: z.string().optional(),
    url: z.string().optional(),
  });

export type GetMiscHotboard = {
  type?: string | undefined;
  keyword?: string | undefined;
  count?: number | undefined;
  results?: Array<GetMiscHotboardResult> | undefined;
};

export const GetMiscHotboard$zodSchema: z.ZodType<GetMiscHotboard> = z.object({
  count: z.int().optional().describe("匹配到的结果数量。"),
  keyword: z.string().optional().describe("搜索关键词。"),
  results: z.array(z.lazy(() => GetMiscHotboardResult$zodSchema)).optional()
    .describe("搜索结果数组。"),
  type: z.string().optional(),
});

export type GetMiscHotboardList = {
  extra?: { [k: string]: any } | undefined;
  hot_value?: string | undefined;
  index?: number | undefined;
  title?: string | undefined;
  url?: string | undefined;
  cover?: string | undefined;
};

export const GetMiscHotboardList$zodSchema: z.ZodType<GetMiscHotboardList> = z
  .object({
    cover: z.string().optional().describe(
      "封面图 URL，音乐类热榜返回专辑封面，其他平台一般不返回。",
    ),
    extra: z.record(z.string(), z.any()).optional().describe(
      "额外信息，不同平台该字段内容不同，例如微博热搜的标签（如“新”“爆”）。",
    ),
    hot_value: z.string().optional(),
    index: z.int().optional(),
    title: z.string().optional(),
    url: z.string().optional(),
  });

export type Root = {
  type?: string | undefined;
  update_time?: string | undefined;
  snapshot_time?: number | undefined;
  list?: Array<GetMiscHotboardList> | undefined;
};

export const Root$zodSchema: z.ZodType<Root> = z.object({
  list: z.array(z.lazy(() => GetMiscHotboardList$zodSchema)).optional()
    .describe("热榜条目列表。"),
  snapshot_time: z.int().optional().describe(
    "时光机模式返回的快照实际时间戳（毫秒）。当前热榜模式下通常不返回。",
  ),
  type: z.string().optional(),
  update_time: z.string().optional().describe(
    "热榜更新时间。时光机无匹配快照时可能为空字符串。",
  ),
});

/**
 * 查询成功！返回指定平台的热榜列表数据。不同模式返回格式不同：默认模式和时光机模式返回 list 数组；搜索模式返回 results 数组。
 */
export type GetMiscHotboardResponseBody = Root | GetMiscHotboard;

export const GetMiscHotboardResponseBody$zodSchema: z.ZodType<
  GetMiscHotboardResponseBody
> = z.union([
  z.lazy(() => Root$zodSchema),
  z.lazy(() => GetMiscHotboard$zodSchema),
]).describe(
  "查询成功！返回指定平台的热榜列表数据。不同模式返回格式不同：默认模式和时光机模式返回 list 数组；搜索模式返回 results 数组。",
);

export type GetMiscHotboardResponse =
  | Root
  | GetMiscHotboard
  | GetMiscHotboardBadRequestResponseBody
  | GetMiscHotboardInternalServerErrorResponseBody
  | GetMiscHotboardBadGatewayResponseBody;

export const GetMiscHotboardResponse$zodSchema: z.ZodType<
  GetMiscHotboardResponse
> = z.union([
  z.union([
    z.lazy(() => Root$zodSchema),
    z.lazy(() => GetMiscHotboard$zodSchema),
  ]),
  z.lazy(() => GetMiscHotboardBadRequestResponseBody$zodSchema),
  z.lazy(() => GetMiscHotboardInternalServerErrorResponseBody$zodSchema),
  z.lazy(() => GetMiscHotboardBadGatewayResponseBody$zodSchema),
]);
