/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetMiscLunartimeRequest = {
  ts?: string | undefined;
  timezone?: string | undefined;
};

export const GetMiscLunartimeRequest$zodSchema: z.ZodType<
  GetMiscLunartimeRequest
> = z.object({
  timezone: z.string().describe(
    "时区名称。支持 IANA 时区（如 Asia/Shanghai）和别名（Shanghai、Beijing）。默认 Asia/Shanghai。",
  ).optional(),
  ts: z.string().describe(
    "Unix 时间戳，支持 10 位秒级或 13 位毫秒级。不传则默认当前时间。",
  ).optional(),
});

/**
 * 请求参数错误。`timezone` 非法时返回 `invalid timezone: xxx`，`ts` 非法时返回 `invalid timestamp: xxx`。
 */
export type GetMiscLunartimeBadRequestResponseBody = {
  code?: number | undefined;
  message?: string | undefined;
};

export const GetMiscLunartimeBadRequestResponseBody$zodSchema: z.ZodType<
  GetMiscLunartimeBadRequestResponseBody
> = z.object({
  code: z.int().optional(),
  message: z.string().optional(),
}).describe(
  "请求参数错误。`timezone` 非法时返回 `invalid timezone: xxx`，`ts` 非法时返回 `invalid timestamp: xxx`。",
);

/**
 * 查询成功，返回指定时间和时区下的农历信息。
 */
export type GetMiscLunartimeResponseBody = {
  query_timestamp?: string | undefined;
  query_timezone?: string | undefined;
  timezone?: string | undefined;
  datetime?: string | undefined;
  datetime_rfc3339?: string | undefined;
  timestamp_unix?: number | undefined;
  weekday?: string | undefined;
  weekday_cn?: string | undefined;
  lunar_year?: number | undefined;
  lunar_month?: number | undefined;
  lunar_day?: number | undefined;
  is_leap_month?: boolean | undefined;
  lunar_year_cn?: string | undefined;
  lunar_month_cn?: string | undefined;
  lunar_day_cn?: string | undefined;
  ganzhi_year?: string | undefined;
  ganzhi_month?: string | undefined;
  ganzhi_day?: string | undefined;
  zodiac?: string | undefined;
  solar_term?: string | undefined;
  lunar_festivals?: Array<string> | undefined;
  solar_festivals?: Array<string> | undefined;
};

export const GetMiscLunartimeResponseBody$zodSchema: z.ZodType<
  GetMiscLunartimeResponseBody
> = z.object({
  datetime: z.string().optional().describe(
    "本地化时间，格式 YYYY-MM-DD HH:mm:ss。",
  ),
  datetime_rfc3339: z.string().optional().describe("RFC3339 时间格式。"),
  ganzhi_day: z.string().optional().describe("干支日。"),
  ganzhi_month: z.string().optional().describe("干支月。"),
  ganzhi_year: z.string().optional().describe("干支年。"),
  is_leap_month: z.boolean().optional().describe("是否闰月。"),
  lunar_day: z.int().optional().describe("农历日期（数字）。"),
  lunar_day_cn: z.string().optional().describe("农历日期中文表示。"),
  lunar_festivals: z.array(z.string()).optional().describe("农历节日数组。"),
  lunar_month: z.int().optional().describe("农历月份（数字）。"),
  lunar_month_cn: z.string().optional().describe("农历月份中文表示。"),
  lunar_year: z.int().optional().describe("农历年份（数字）。"),
  lunar_year_cn: z.string().optional().describe("农历年份中文表示。"),
  query_timestamp: z.string().optional().describe("原始 ts 入参。"),
  query_timezone: z.string().optional().describe("原始 timezone 入参。"),
  solar_festivals: z.array(z.string()).optional().describe("公历节日数组。"),
  solar_term: z.string().optional().describe(
    "节气名称。有值时返回，无值时可能为空字符串或不返回。",
  ),
  timestamp_unix: z.int().optional().describe("秒级 Unix 时间戳。"),
  timezone: z.string().optional().describe("解析后的时区。"),
  weekday: z.string().optional().describe("星期英文。"),
  weekday_cn: z.string().optional().describe("星期中文。"),
  zodiac: z.string().optional().describe("生肖。"),
}).describe("查询成功，返回指定时间和时区下的农历信息。");

export type GetMiscLunartimeResponse =
  | GetMiscLunartimeResponseBody
  | GetMiscLunartimeBadRequestResponseBody;

export const GetMiscLunartimeResponse$zodSchema: z.ZodType<
  GetMiscLunartimeResponse
> = z.union([
  z.lazy(() => GetMiscLunartimeResponseBody$zodSchema),
  z.lazy(() => GetMiscLunartimeBadRequestResponseBody$zodSchema),
]);
