/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetSayingDetails = {};

export const GetSayingDetails$zodSchema: z.ZodType<GetSayingDetails> = z.object(
  {},
);

/**
 * 当语料库为空或无法读取时。
 */
export type GetSayingInternalServerErrorResponseBody = {
  code?: string | undefined;
  details?: GetSayingDetails | undefined;
  message?: string | undefined;
};

export const GetSayingInternalServerErrorResponseBody$zodSchema: z.ZodType<
  GetSayingInternalServerErrorResponseBody
> = z.object({
  code: z.string().optional(),
  details: z.lazy(() => GetSayingDetails$zodSchema).optional(),
  message: z.string().optional(),
}).describe("当语料库为空或无法读取时。");

/**
 * 请求成功！返回一条随机的语录。
 */
export type GetSayingResponseBody = { text?: string | undefined };

export const GetSayingResponseBody$zodSchema: z.ZodType<GetSayingResponseBody> =
  z.object({
    text: z.string().optional(),
  }).describe("请求成功！返回一条随机的语录。");

export type GetSayingResponse =
  | GetSayingResponseBody
  | GetSayingInternalServerErrorResponseBody;

export const GetSayingResponse$zodSchema: z.ZodType<GetSayingResponse> = z
  .union([
    z.lazy(() => GetSayingResponseBody$zodSchema),
    z.lazy(() => GetSayingInternalServerErrorResponseBody$zodSchema),
  ]);
