/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetSocialQqGroupinfoRequest = { group_id: string };

export const GetSocialQqGroupinfoRequest$zodSchema: z.ZodType<
  GetSocialQqGroupinfoRequest
> = z.object({
  group_id: z.string().describe("QQ群号，长度5-12位"),
});

/**
 * QQ群不存在或暂时无法访问
 */
export type GetSocialQqGroupinfoNotFoundResponseBody = {
  error?: string | undefined;
};

export const GetSocialQqGroupinfoNotFoundResponseBody$zodSchema: z.ZodType<
  GetSocialQqGroupinfoNotFoundResponseBody
> = z.object({
  error: z.string().optional(),
}).describe("QQ群不存在或暂时无法访问");

export type GetSocialQqGroupinfoDetails = {};

export const GetSocialQqGroupinfoDetails$zodSchema: z.ZodType<
  GetSocialQqGroupinfoDetails
> = z.object({});

/**
 * 缺少或无效的group_id参数
 */
export type GetSocialQqGroupinfoBadRequestResponseBody = {
  code?: string | undefined;
  details?: GetSocialQqGroupinfoDetails | undefined;
  message?: string | undefined;
};

export const GetSocialQqGroupinfoBadRequestResponseBody$zodSchema: z.ZodType<
  GetSocialQqGroupinfoBadRequestResponseBody
> = z.object({
  code: z.string().optional(),
  details: z.lazy(() => GetSocialQqGroupinfoDetails$zodSchema).optional(),
  message: z.string().optional(),
}).describe("缺少或无效的group_id参数");

/**
 * 成功响应，返回QQ群的详细信息
 */
export type GetSocialQqGroupinfoResponseBody = {
  group_id?: string | undefined;
  group_name?: string | undefined;
  avatar_url?: string | undefined;
  description?: string | undefined;
  tag?: string | undefined;
  join_url?: string | undefined;
  last_updated?: string | undefined;
  member_count?: number | undefined;
  max_member_count?: number | undefined;
  active_member_num?: number | undefined;
  owner_uin?: string | undefined;
  owner_uid?: string | undefined;
  create_time?: number | undefined;
  create_time_str?: string | undefined;
  group_grade?: number | undefined;
  group_memo?: string | undefined;
  cert_type?: number | undefined;
  cert_text?: string | undefined;
};

export const GetSocialQqGroupinfoResponseBody$zodSchema: z.ZodType<
  GetSocialQqGroupinfoResponseBody
> = z.object({
  active_member_num: z.int().optional().describe(
    "活跃成员数（可选，部分群有此数据）",
  ),
  avatar_url: z.string().optional().describe("群头像URL（标准尺寸100x100）"),
  cert_text: z.string().optional().describe("认证说明文本（可选）"),
  cert_type: z.int().optional().describe("认证类型（0=未认证，可选）"),
  create_time: z.int().optional().describe("建群时间戳（Unix时间戳，可选）"),
  create_time_str: z.string().optional().describe(
    "建群时间格式化字符串（可选）",
  ),
  description: z.string().optional().describe("群描述/简介"),
  group_grade: z.int().optional().describe("群等级（可选）"),
  group_id: z.string().optional().describe("群号"),
  group_memo: z.string().optional().describe("群公告/简介（可选）"),
  group_name: z.string().optional().describe("群名称"),
  join_url: z.string().optional().describe("加群链接（QR码URL）"),
  last_updated: z.string().optional().describe("最后更新时间（ISO 8601格式）"),
  max_member_count: z.int().optional().describe("最大成员数"),
  member_count: z.int().optional().describe("当前成员数"),
  owner_uid: z.string().optional().describe("群主UID（可选）"),
  owner_uin: z.string().optional().describe("群主QQ号（可选）"),
  tag: z.string().optional().describe("群标签"),
}).describe("成功响应，返回QQ群的详细信息");

export type GetSocialQqGroupinfoResponse =
  | GetSocialQqGroupinfoResponseBody
  | GetSocialQqGroupinfoBadRequestResponseBody
  | GetSocialQqGroupinfoNotFoundResponseBody;

export const GetSocialQqGroupinfoResponse$zodSchema: z.ZodType<
  GetSocialQqGroupinfoResponse
> = z.union([
  z.lazy(() => GetSocialQqGroupinfoResponseBody$zodSchema),
  z.lazy(() => GetSocialQqGroupinfoBadRequestResponseBody$zodSchema),
  z.lazy(() => GetSocialQqGroupinfoNotFoundResponseBody$zodSchema),
]);
