/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetSocialBilibiliUserinfoRequest = { uid: string };

export const GetSocialBilibiliUserinfoRequest$zodSchema: z.ZodType<
  GetSocialBilibiliUserinfoRequest
> = z.object({
  uid: z.string().describe("Bilibili用户的UID"),
});

export type GetSocialBilibiliUserinfoBadGatewayDetails = {};

export const GetSocialBilibiliUserinfoBadGatewayDetails$zodSchema: z.ZodType<
  GetSocialBilibiliUserinfoBadGatewayDetails
> = z.object({});

/**
 * 暂时无法获取相关数据，请稍后重试。
 */
export type GetSocialBilibiliUserinfoBadGatewayResponseBody = {
  code?: string | undefined;
  details?: GetSocialBilibiliUserinfoBadGatewayDetails | undefined;
  message?: string | undefined;
};

export const GetSocialBilibiliUserinfoBadGatewayResponseBody$zodSchema:
  z.ZodType<GetSocialBilibiliUserinfoBadGatewayResponseBody> = z.object({
    code: z.string().optional(),
    details: z.lazy(() => GetSocialBilibiliUserinfoBadGatewayDetails$zodSchema)
      .optional(),
    message: z.string().optional(),
  }).describe("暂时无法获取相关数据，请稍后重试。");

export type GetSocialBilibiliUserinfoNotFoundDetails = {};

export const GetSocialBilibiliUserinfoNotFoundDetails$zodSchema: z.ZodType<
  GetSocialBilibiliUserinfoNotFoundDetails
> = z.object({});

/**
 * Bilibili用户不存在
 */
export type GetSocialBilibiliUserinfoNotFoundResponseBody = {
  code?: string | undefined;
  details?: GetSocialBilibiliUserinfoNotFoundDetails | undefined;
  message?: string | undefined;
};

export const GetSocialBilibiliUserinfoNotFoundResponseBody$zodSchema: z.ZodType<
  GetSocialBilibiliUserinfoNotFoundResponseBody
> = z.object({
  code: z.string().optional(),
  details: z.lazy(() => GetSocialBilibiliUserinfoNotFoundDetails$zodSchema)
    .optional(),
  message: z.string().optional(),
}).describe("Bilibili用户不存在");

export type GetSocialBilibiliUserinfoBadRequestDetails = {};

export const GetSocialBilibiliUserinfoBadRequestDetails$zodSchema: z.ZodType<
  GetSocialBilibiliUserinfoBadRequestDetails
> = z.object({});

/**
 * 缺少uid参数
 */
export type GetSocialBilibiliUserinfoBadRequestResponseBody = {
  code?: string | undefined;
  details?: GetSocialBilibiliUserinfoBadRequestDetails | undefined;
  message?: string | undefined;
};

export const GetSocialBilibiliUserinfoBadRequestResponseBody$zodSchema:
  z.ZodType<GetSocialBilibiliUserinfoBadRequestResponseBody> = z.object({
    code: z.string().optional(),
    details: z.lazy(() => GetSocialBilibiliUserinfoBadRequestDetails$zodSchema)
      .optional(),
    message: z.string().optional(),
  }).describe("缺少uid参数");

/**
 * 查询成功！返回 B 站用户公开数据。
 */
export type GetSocialBilibiliUserinfoResponseBody = {
  mid?: number | undefined;
  name?: string | undefined;
  sex?: string | undefined;
  face?: string | undefined;
  sign?: string | undefined;
  level?: number | undefined;
  birthday?: string | undefined;
  vip_type?: number | undefined;
  vip_status?: number | undefined;
  following?: number | undefined;
  follower?: number | undefined;
  archive_count?: number | undefined;
  article_count?: number | undefined;
};

export const GetSocialBilibiliUserinfoResponseBody$zodSchema: z.ZodType<
  GetSocialBilibiliUserinfoResponseBody
> = z.object({
  archive_count: z.int().optional(),
  article_count: z.int().optional(),
  birthday: z.string().optional(),
  face: z.string().optional(),
  follower: z.int().optional(),
  following: z.int().optional(),
  level: z.int().optional(),
  mid: z.int().optional(),
  name: z.string().optional(),
  sex: z.string().optional(),
  sign: z.string().optional(),
  vip_status: z.int().optional(),
  vip_type: z.int().optional(),
}).describe("查询成功！返回 B 站用户公开数据。");

export type GetSocialBilibiliUserinfoResponse =
  | GetSocialBilibiliUserinfoResponseBody
  | GetSocialBilibiliUserinfoBadRequestResponseBody
  | GetSocialBilibiliUserinfoNotFoundResponseBody
  | GetSocialBilibiliUserinfoBadGatewayResponseBody;

export const GetSocialBilibiliUserinfoResponse$zodSchema: z.ZodType<
  GetSocialBilibiliUserinfoResponse
> = z.union([
  z.lazy(() => GetSocialBilibiliUserinfoResponseBody$zodSchema),
  z.lazy(() => GetSocialBilibiliUserinfoBadRequestResponseBody$zodSchema),
  z.lazy(() => GetSocialBilibiliUserinfoNotFoundResponseBody$zodSchema),
  z.lazy(() => GetSocialBilibiliUserinfoBadGatewayResponseBody$zodSchema),
]);
