/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * 输出格式。可以传 `bmp`、`rgb565` 或 `rgb888`，不传时默认是 `bmp`。
 */
export const PostImageDecodeFormat = {
  Bmp: "bmp",
  Rgb565: "rgb565",
  Rgb888: "rgb888",
} as const;
/**
 * 输出格式。可以传 `bmp`、`rgb565` 或 `rgb888`，不传时默认是 `bmp`。
 */
export type PostImageDecodeFormat = ClosedEnum<typeof PostImageDecodeFormat>;

export const PostImageDecodeFormat$zodSchema = z.enum([
  "bmp",
  "rgb565",
  "rgb888",
]).describe(
  "输出格式。可以传 `bmp`、`rgb565` 或 `rgb888`，不传时默认是 `bmp`。",
);

/**
 * BMP 输出的颜色模式。只有在 `format=bmp` 时才生效，可以传 `RGB565` 或 `RGB888`，不传时默认是 `RGB888`。
 */
export const ColorMode = {
  Rgb565: "RGB565",
  Rgb888: "RGB888",
} as const;
/**
 * BMP 输出的颜色模式。只有在 `format=bmp` 时才生效，可以传 `RGB565` 或 `RGB888`，不传时默认是 `RGB888`。
 */
export type ColorMode = ClosedEnum<typeof ColorMode>;

export const ColorMode$zodSchema = z.enum([
  "RGB565",
  "RGB888",
]).describe(
  "BMP 输出的颜色模式。只有在 `format=bmp` 时才生效，可以传 `RGB565` 或 `RGB888`，不传时默认是 `RGB888`。",
);

/**
 * 缩放模式。可以传 `contain`、`cover` 或 `fill`，不传时默认是 `contain`。当传 `cover` 或 `fill` 时，`width` 和 `height` 都要传。
 */
export const Fit = {
  Contain: "contain",
  Cover: "cover",
  Fill: "fill",
} as const;
/**
 * 缩放模式。可以传 `contain`、`cover` 或 `fill`，不传时默认是 `contain`。当传 `cover` 或 `fill` 时，`width` 和 `height` 都要传。
 */
export type Fit = ClosedEnum<typeof Fit>;

export const Fit$zodSchema = z.enum([
  "contain",
  "cover",
  "fill",
]).describe(
  "缩放模式。可以传 `contain`、`cover` 或 `fill`，不传时默认是 `contain`。当传 `cover` 或 `fill` 时，`width` 和 `height` 都要传。",
);

export type PostImageDecodeFile2 = {
  fileName: string;
  content: Uint8Array | string;
};

export const PostImageDecodeFile2$zodSchema: z.ZodType<PostImageDecodeFile2> = z
  .object({
    content: z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    fileName: z.string(),
  });

export type PostImageDecodeRequestBody2 = {
  file?: PostImageDecodeFile2 | Blob | undefined;
  url: string;
};

export const PostImageDecodeRequestBody2$zodSchema: z.ZodType<
  PostImageDecodeRequestBody2
> = z.object({
  file: z.lazy(() => PostImageDecodeFile2$zodSchema).optional().describe(
    "要处理的图片文件。这个接口适合直接上传 JPG、JPEG、PNG、WebP、BMP 等常见格式。",
  ),
  url: z.string().describe("要处理的图片链接。适合不方便直接上传文件时使用。"),
});

export type PostImageDecodeFile1 = {
  fileName: string;
  content: Uint8Array | string;
};

export const PostImageDecodeFile1$zodSchema: z.ZodType<PostImageDecodeFile1> = z
  .object({
    content: z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    fileName: z.string(),
  });

export type PostImageDecodeRequestBody1 = {
  file: PostImageDecodeFile1 | Blob;
  url?: string | undefined;
};

export const PostImageDecodeRequestBody1$zodSchema: z.ZodType<
  PostImageDecodeRequestBody1
> = z.object({
  file: z.lazy(() => PostImageDecodeFile1$zodSchema).describe(
    "要处理的图片文件。这个接口适合直接上传 JPG、JPEG、PNG、WebP、BMP 等常见格式。",
  ),
  url: z.string().optional().describe(
    "要处理的图片链接。适合不方便直接上传文件时使用。",
  ),
});

/**
 * 包含图片来源的表单数据。`file` 和 `url` 至少传一个；如果同时传，优先使用 `file`。
 */
export type PostImageDecodeRequestBody =
  | PostImageDecodeRequestBody1
  | PostImageDecodeRequestBody2;

export const PostImageDecodeRequestBody$zodSchema: z.ZodType<
  PostImageDecodeRequestBody
> = z.union([
  z.lazy(() => PostImageDecodeRequestBody1$zodSchema),
  z.lazy(() => PostImageDecodeRequestBody2$zodSchema),
]).describe(
  "包含图片来源的表单数据。`file` 和 `url` 至少传一个；如果同时传，优先使用 `file`。",
);

export type PostImageDecodeRequest = {
  width?: number | undefined;
  height?: number | undefined;
  max_width?: number | undefined;
  max_height?: number | undefined;
  format?: PostImageDecodeFormat | undefined;
  color_mode?: ColorMode | undefined;
  fit?: Fit | undefined;
  background?: string | undefined;
  body: PostImageDecodeRequestBody1 | PostImageDecodeRequestBody2;
};

export const PostImageDecodeRequest$zodSchema: z.ZodType<
  PostImageDecodeRequest
> = z.object({
  background: z.string().default("black").describe(
    "背景色。可以传 `black`、`white` 或 `#RRGGBB`，不传时默认是 `black`。",
  ),
  body: z.union([
    z.lazy(() => PostImageDecodeRequestBody1$zodSchema),
    z.lazy(() => PostImageDecodeRequestBody2$zodSchema),
  ]).describe(
    "包含图片来源的表单数据。`file` 和 `url` 至少传一个；如果同时传，优先使用 `file`。",
  ),
  color_mode: ColorMode$zodSchema.default("RGB888").describe(
    "BMP 输出的颜色模式。只有在 `format=bmp` 时才生效，可以传 `RGB565` 或 `RGB888`，不传时默认是 `RGB888`。",
  ),
  fit: Fit$zodSchema.default("contain").describe(
    "缩放模式。可以传 `contain`、`cover` 或 `fill`，不传时默认是 `contain`。当传 `cover` 或 `fill` 时，`width` 和 `height` 都要传。",
  ),
  format: PostImageDecodeFormat$zodSchema.default("bmp").describe(
    "输出格式。可以传 `bmp`、`rgb565` 或 `rgb888`，不传时默认是 `bmp`。",
  ),
  height: z.int().describe(
    "目标高度，单位是像素。可以单独传，也可以和 `width` 一起传。与 `max_width`、`max_height` 互斥。",
  ).optional(),
  max_height: z.int().describe(
    "最大高度，单位是像素。只有在不传 `width`、`height` 时才生效，会按原比例缩放。",
  ).optional(),
  max_width: z.int().describe(
    "最大宽度，单位是像素。只有在不传 `width`、`height` 时才生效，会按原比例缩放。",
  ).optional(),
  width: z.int().describe(
    "目标宽度，单位是像素。可以单独传，也可以和 `height` 一起传。与 `max_width`、`max_height` 互斥。",
  ).optional(),
});

/**
 * 获取图片超时。
 */
export type PostImageDecodeGatewayTimeoutResponseBody = {
  error?: string | undefined;
};

export const PostImageDecodeGatewayTimeoutResponseBody$zodSchema: z.ZodType<
  PostImageDecodeGatewayTimeoutResponseBody
> = z.object({
  error: z.string().optional(),
}).describe("获取图片超时。");

/**
 * 当前图片处理任务过多，或者暂时无法获取图片。
 */
export type PostImageDecodeServiceUnavailableResponseBody = {
  error?: string | undefined;
};

export const PostImageDecodeServiceUnavailableResponseBody$zodSchema: z.ZodType<
  PostImageDecodeServiceUnavailableResponseBody
> = z.object({
  error: z.string().optional(),
}).describe("当前图片处理任务过多，或者暂时无法获取图片。");

/**
 * 图片下载失败，或者图片链接返回的不是可识别的图片内容。
 */
export type PostImageDecodeBadGatewayResponseBody = {
  error?: string | undefined;
};

export const PostImageDecodeBadGatewayResponseBody$zodSchema: z.ZodType<
  PostImageDecodeBadGatewayResponseBody
> = z.object({
  error: z.string().optional(),
}).describe("图片下载失败，或者图片链接返回的不是可识别的图片内容。");

/**
 * 服务器处理失败，例如图片编码阶段发生错误。
 */
export type PostImageDecodeInternalServerErrorResponseBody = {
  error?: string | undefined;
};

export const PostImageDecodeInternalServerErrorResponseBody$zodSchema:
  z.ZodType<PostImageDecodeInternalServerErrorResponseBody> = z.object({
    error: z.string().optional(),
  }).describe("服务器处理失败，例如图片编码阶段发生错误。");

/**
 * 上传图片体积、拉取到的图片体积、源图片像素，或者输出图片像素超过限制。
 */
export type PostImageDecodeRequestEntityTooLargeResponseBody = {
  error?: string | undefined;
};

export const PostImageDecodeRequestEntityTooLargeResponseBody$zodSchema:
  z.ZodType<PostImageDecodeRequestEntityTooLargeResponseBody> = z.object({
    error: z.string().optional(),
  }).describe(
    "上传图片体积、拉取到的图片体积、源图片像素，或者输出图片像素超过限制。",
  );

/**
 * 请求参数不正确，或者传入的文件和链接都不是可处理的图片内容。
 */
export type PostImageDecodeBadRequestResponseBody = {
  error?: string | undefined;
};

export const PostImageDecodeBadRequestResponseBody$zodSchema: z.ZodType<
  PostImageDecodeBadRequestResponseBody
> = z.object({
  error: z.string().optional(),
}).describe("请求参数不正确，或者传入的文件和链接都不是可处理的图片内容。");

export type PostImageDecodeResponseResult =
  | Uint8Array
  | string
  | Uint8Array
  | string
  | PostImageDecodeBadRequestResponseBody
  | PostImageDecodeRequestEntityTooLargeResponseBody
  | PostImageDecodeInternalServerErrorResponseBody
  | PostImageDecodeBadGatewayResponseBody
  | PostImageDecodeServiceUnavailableResponseBody
  | PostImageDecodeGatewayTimeoutResponseBody;

export const PostImageDecodeResponseResult$zodSchema: z.ZodType<
  PostImageDecodeResponseResult
> = z.union([
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.lazy(() => PostImageDecodeBadRequestResponseBody$zodSchema),
  z.lazy(() => PostImageDecodeRequestEntityTooLargeResponseBody$zodSchema),
  z.lazy(() => PostImageDecodeInternalServerErrorResponseBody$zodSchema),
  z.lazy(() => PostImageDecodeBadGatewayResponseBody$zodSchema),
  z.lazy(() => PostImageDecodeServiceUnavailableResponseBody$zodSchema),
  z.lazy(() => PostImageDecodeGatewayTimeoutResponseBody$zodSchema),
]);

export type PostImageDecodeResponse = {
  Headers: { [k: string]: Array<string> };
  Result:
    | Uint8Array
    | string
    | Uint8Array
    | string
    | PostImageDecodeBadRequestResponseBody
    | PostImageDecodeRequestEntityTooLargeResponseBody
    | PostImageDecodeInternalServerErrorResponseBody
    | PostImageDecodeBadGatewayResponseBody
    | PostImageDecodeServiceUnavailableResponseBody
    | PostImageDecodeGatewayTimeoutResponseBody;
};

export const PostImageDecodeResponse$zodSchema: z.ZodType<
  PostImageDecodeResponse
> = z.object({
  Headers: z.record(z.string(), z.array(z.string())).default({}),
  Result: z.union([
    z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    z.lazy(() => PostImageDecodeBadRequestResponseBody$zodSchema),
    z.lazy(() => PostImageDecodeRequestEntityTooLargeResponseBody$zodSchema),
    z.lazy(() => PostImageDecodeInternalServerErrorResponseBody$zodSchema),
    z.lazy(() => PostImageDecodeBadGatewayResponseBody$zodSchema),
    z.lazy(() => PostImageDecodeServiceUnavailableResponseBody$zodSchema),
    z.lazy(() => PostImageDecodeGatewayTimeoutResponseBody$zodSchema),
  ]),
});
