/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * 响应格式。传 `json` 时返回 JSON 包裹的 HTML 片段；传 `html` 时直接返回 `text/html`，并且响应内容会自动带完整的网页结构，适合浏览器预览或直接保存为网页文件。默认是 `json`。
 */
export const PostTextMarkdownToHtmlFormat = {
  Json: "json",
  Html: "html",
} as const;
/**
 * 响应格式。传 `json` 时返回 JSON 包裹的 HTML 片段；传 `html` 时直接返回 `text/html`，并且响应内容会自动带完整的网页结构，适合浏览器预览或直接保存为网页文件。默认是 `json`。
 */
export type PostTextMarkdownToHtmlFormat = ClosedEnum<
  typeof PostTextMarkdownToHtmlFormat
>;

export const PostTextMarkdownToHtmlFormat$zodSchema = z.enum([
  "json",
  "html",
]).describe(
  "响应格式。传 `json` 时返回 JSON 包裹的 HTML 片段；传 `html` 时直接返回 `text/html`，并且响应内容会自动带完整的网页结构，适合浏览器预览或直接保存为网页文件。默认是 `json`。",
);

/**
 * 请求体使用 `application/json`。`text` 必填；`format` 和 `sanitize` 可选。
 */
export type PostTextMarkdownToHtmlRequest = {
  text: string;
  format?: PostTextMarkdownToHtmlFormat | undefined;
  sanitize?: boolean | undefined;
};

export const PostTextMarkdownToHtmlRequest$zodSchema: z.ZodType<
  PostTextMarkdownToHtmlRequest
> = z.object({
  format: PostTextMarkdownToHtmlFormat$zodSchema.default("json").describe(
    "响应格式。传 `json` 时返回 JSON 包裹的 HTML 片段；传 `html` 时直接返回 `text/html`，并且响应内容会自动带完整的网页结构，适合浏览器预览或直接保存为网页文件。默认是 `json`。",
  ),
  sanitize: z.boolean().default(true).describe(
    "是否开启安全模式，过滤掉用户输入中的风险脚本。默认是 `true`。",
  ),
  text: z.string().describe("原始 Markdown 字符串，最大不超过 1MB。"),
}).describe(
  "请求体使用 `application/json`。`text` 必填；`format` 和 `sanitize` 可选。",
);

/**
 * 服务暂时不可用。
 */
export type PostTextMarkdownToHtmlServiceUnavailableResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToHtmlServiceUnavailableResponseBody$zodSchema:
  z.ZodType<PostTextMarkdownToHtmlServiceUnavailableResponseBody> = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }).describe("服务暂时不可用。");

/**
 * 转换过程中发生错误，请稍后再试。
 */
export type PostTextMarkdownToHtmlInternalServerErrorResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToHtmlInternalServerErrorResponseBody$zodSchema:
  z.ZodType<PostTextMarkdownToHtmlInternalServerErrorResponseBody> = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }).describe("转换过程中发生错误，请稍后再试。");

/**
 * Markdown 文本超过当前大小限制。
 */
export type PostTextMarkdownToHtmlRequestEntityTooLargeResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToHtmlRequestEntityTooLargeResponseBody$zodSchema:
  z.ZodType<PostTextMarkdownToHtmlRequestEntityTooLargeResponseBody> = z.object(
    {
      code: z.string().optional(),
      message: z.string().optional(),
    },
  ).describe("Markdown 文本超过当前大小限制。");

export type PostTextMarkdownToHtml2 = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToHtml2$zodSchema: z.ZodType<
  PostTextMarkdownToHtml2
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

export type PostTextMarkdownToHtmlMarkdown = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToHtmlMarkdown$zodSchema: z.ZodType<
  PostTextMarkdownToHtmlMarkdown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

export type PostTextMarkdownToHtml1 = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToHtml1$zodSchema: z.ZodType<
  PostTextMarkdownToHtml1
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

/**
 * 请求参数错误。可能是请求体格式错误、`text` 为空，或者 `format` 取值不合法。
 */
export type PostTextMarkdownToHtmlResponseBodyUnion =
  | PostTextMarkdownToHtml1
  | PostTextMarkdownToHtmlMarkdown
  | PostTextMarkdownToHtml2;

export const PostTextMarkdownToHtmlResponseBodyUnion$zodSchema: z.ZodType<
  PostTextMarkdownToHtmlResponseBodyUnion
> = z.union([
  z.lazy(() => PostTextMarkdownToHtml1$zodSchema),
  z.lazy(() => PostTextMarkdownToHtmlMarkdown$zodSchema),
  z.lazy(() => PostTextMarkdownToHtml2$zodSchema),
]).describe(
  "请求参数错误。可能是请求体格式错误、`text` 为空，或者 `format` 取值不合法。",
);

export type PostTextMarkdownToHtmlData = { html?: string | undefined };

export const PostTextMarkdownToHtmlData$zodSchema: z.ZodType<
  PostTextMarkdownToHtmlData
> = z.object({
  html: z.string().optional().describe(
    "转换后的 HTML 字符串，内容是带样式的 HTML 片段。",
  ),
});

/**
 * 转换成功。具体返回 JSON 还是纯 HTML，由 `format` 参数决定。
 */
export type PostTextMarkdownToHtmlResponseBody = {
  data?: PostTextMarkdownToHtmlData | undefined;
};

export const PostTextMarkdownToHtmlResponseBody$zodSchema: z.ZodType<
  PostTextMarkdownToHtmlResponseBody
> = z.object({
  data: z.lazy(() => PostTextMarkdownToHtmlData$zodSchema).optional(),
}).describe("转换成功。具体返回 JSON 还是纯 HTML，由 `format` 参数决定。");

export type PostTextMarkdownToHtmlResponse =
  | PostTextMarkdownToHtmlResponseBody
  | string
  | PostTextMarkdownToHtml1
  | PostTextMarkdownToHtmlMarkdown
  | PostTextMarkdownToHtml2
  | PostTextMarkdownToHtmlRequestEntityTooLargeResponseBody
  | PostTextMarkdownToHtmlInternalServerErrorResponseBody
  | PostTextMarkdownToHtmlServiceUnavailableResponseBody;

export const PostTextMarkdownToHtmlResponse$zodSchema: z.ZodType<
  PostTextMarkdownToHtmlResponse
> = z.union([
  z.lazy(() => PostTextMarkdownToHtmlResponseBody$zodSchema),
  z.string().describe(
    "转换成功。具体返回 JSON 还是纯 HTML，由 `format` 参数决定。",
  ),
  z.union([
    z.lazy(() => PostTextMarkdownToHtml1$zodSchema),
    z.lazy(() => PostTextMarkdownToHtmlMarkdown$zodSchema),
    z.lazy(() => PostTextMarkdownToHtml2$zodSchema),
  ]),
  z.lazy(() =>
    PostTextMarkdownToHtmlRequestEntityTooLargeResponseBody$zodSchema
  ),
  z.lazy(() => PostTextMarkdownToHtmlInternalServerErrorResponseBody$zodSchema),
  z.lazy(() => PostTextMarkdownToHtmlServiceUnavailableResponseBody$zodSchema),
]);
