/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * PDF 的排版主题。可选 `github`、`minimal`、`light`、`dark`，默认是 `github`。
 */
export const Theme = {
  Github: "github",
  Minimal: "minimal",
  Light: "light",
  Dark: "dark",
} as const;
/**
 * PDF 的排版主题。可选 `github`、`minimal`、`light`、`dark`，默认是 `github`。
 */
export type Theme = ClosedEnum<typeof Theme>;

export const Theme$zodSchema = z.enum([
  "github",
  "minimal",
  "light",
  "dark",
]).describe(
  "PDF 的排版主题。可选 `github`、`minimal`、`light`、`dark`，默认是 `github`。",
);

/**
 * PDF 的纸张大小。可选 `A4` 或 `Letter`，默认是 `A4`。
 */
export const PaperSize = {
  A4: "A4",
  Letter: "Letter",
} as const;
/**
 * PDF 的纸张大小。可选 `A4` 或 `Letter`，默认是 `A4`。
 */
export type PaperSize = ClosedEnum<typeof PaperSize>;

export const PaperSize$zodSchema = z.enum([
  "A4",
  "Letter",
]).describe("PDF 的纸张大小。可选 `A4` 或 `Letter`，默认是 `A4`。");

/**
 * 请求体使用 `application/json`。`text` 必填，`theme` 和 `paper_size` 可选。
 */
export type PostTextMarkdownToPdfRequest = {
  text: string;
  theme?: Theme | undefined;
  paper_size?: PaperSize | undefined;
};

export const PostTextMarkdownToPdfRequest$zodSchema: z.ZodType<
  PostTextMarkdownToPdfRequest
> = z.object({
  paper_size: PaperSize$zodSchema.default("A4").describe(
    "PDF 的纸张大小。可选 `A4` 或 `Letter`，默认是 `A4`。",
  ),
  text: z.string().describe("原始 Markdown 字符串，最大不超过 1MB。"),
  theme: Theme$zodSchema.default("github").describe(
    "PDF 的排版主题。可选 `github`、`minimal`、`light`、`dark`，默认是 `github`。",
  ),
}).describe(
  "请求体使用 `application/json`。`text` 必填，`theme` 和 `paper_size` 可选。",
);

/**
 * Markdown 中引用的图片下载超时。
 */
export type PostTextMarkdownToPdfGatewayTimeoutResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToPdfGatewayTimeoutResponseBody$zodSchema:
  z.ZodType<PostTextMarkdownToPdfGatewayTimeoutResponseBody> = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }).describe("Markdown 中引用的图片下载超时。");

export type ServiceUnavailable2 = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ServiceUnavailable2$zodSchema: z.ZodType<ServiceUnavailable2> = z
  .object({
    code: z.string().optional(),
    message: z.string().optional(),
  });

export type ServiceUnavailable1 = {
  code?: string | undefined;
  message?: string | undefined;
};

export const ServiceUnavailable1$zodSchema: z.ZodType<ServiceUnavailable1> = z
  .object({
    code: z.string().optional(),
    message: z.string().optional(),
  });

/**
 * PDF 渲染服务暂时不可用。
 */
export type PostTextMarkdownToPdfServiceUnavailableResponseBody =
  | ServiceUnavailable1
  | ServiceUnavailable2;

export const PostTextMarkdownToPdfServiceUnavailableResponseBody$zodSchema:
  z.ZodType<PostTextMarkdownToPdfServiceUnavailableResponseBody> = z.union([
    z.lazy(() => ServiceUnavailable1$zodSchema),
    z.lazy(() => ServiceUnavailable2$zodSchema),
  ]).describe("PDF 渲染服务暂时不可用。");

/**
 * Markdown 中引用的图片下载失败，或远端返回的不是可识别的图片内容。
 */
export type PostTextMarkdownToPdfBadGatewayResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToPdfBadGatewayResponseBody$zodSchema: z.ZodType<
  PostTextMarkdownToPdfBadGatewayResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe(
  "Markdown 中引用的图片下载失败，或远端返回的不是可识别的图片内容。",
);

/**
 * PDF 生成失败，请稍后再试。
 */
export type PostTextMarkdownToPdfInternalServerErrorResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToPdfInternalServerErrorResponseBody$zodSchema:
  z.ZodType<PostTextMarkdownToPdfInternalServerErrorResponseBody> = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }).describe("PDF 生成失败，请稍后再试。");

export type RequestEntityTooLarge = {
  code?: string | undefined;
  message?: string | undefined;
};

export const RequestEntityTooLarge$zodSchema: z.ZodType<RequestEntityTooLarge> =
  z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  });

export type RequestEntityTooLargeMarkdown = {
  code?: string | undefined;
  message?: string | undefined;
};

export const RequestEntityTooLargeMarkdown$zodSchema: z.ZodType<
  RequestEntityTooLargeMarkdown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

/**
 * Markdown 文本，或 Markdown 中引用的图片资源超过当前大小限制。
 */
export type PostTextMarkdownToPdfRequestEntityTooLargeResponseBody =
  | RequestEntityTooLargeMarkdown
  | RequestEntityTooLarge;

export const PostTextMarkdownToPdfRequestEntityTooLargeResponseBody$zodSchema:
  z.ZodType<PostTextMarkdownToPdfRequestEntityTooLargeResponseBody> = z.union([
    z.lazy(() => RequestEntityTooLargeMarkdown$zodSchema),
    z.lazy(() => RequestEntityTooLarge$zodSchema),
  ]).describe("Markdown 文本，或 Markdown 中引用的图片资源超过当前大小限制。");

export type PostTextMarkdownToPdfBadRequest5 = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToPdfBadRequest5$zodSchema: z.ZodType<
  PostTextMarkdownToPdfBadRequest5
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

export type PostTextMarkdownToPdfBadRequest4 = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToPdfBadRequest4$zodSchema: z.ZodType<
  PostTextMarkdownToPdfBadRequest4
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

export type Html = { code?: string | undefined; message?: string | undefined };

export const Html$zodSchema: z.ZodType<Html> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

export type PostTextMarkdownToPdfBadRequest3 = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToPdfBadRequest3$zodSchema: z.ZodType<
  PostTextMarkdownToPdfBadRequest3
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

export type PostTextMarkdownToPdfBadRequest2 = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToPdfBadRequest2$zodSchema: z.ZodType<
  PostTextMarkdownToPdfBadRequest2
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

export type PostTextMarkdownToPdfBadRequestMarkdown = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToPdfBadRequestMarkdown$zodSchema: z.ZodType<
  PostTextMarkdownToPdfBadRequestMarkdown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

export type PostTextMarkdownToPdfBadRequest1 = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostTextMarkdownToPdfBadRequest1$zodSchema: z.ZodType<
  PostTextMarkdownToPdfBadRequest1
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
});

/**
 * 请求参数不合法，或者 Markdown 内容包含当前不允许的内容。
 */
export type PostTextMarkdownToPdfBadRequestResponseBody =
  | PostTextMarkdownToPdfBadRequest1
  | PostTextMarkdownToPdfBadRequestMarkdown
  | PostTextMarkdownToPdfBadRequest2
  | PostTextMarkdownToPdfBadRequest3
  | Html
  | PostTextMarkdownToPdfBadRequest4
  | PostTextMarkdownToPdfBadRequest5;

export const PostTextMarkdownToPdfBadRequestResponseBody$zodSchema: z.ZodType<
  PostTextMarkdownToPdfBadRequestResponseBody
> = z.union([
  z.lazy(() => PostTextMarkdownToPdfBadRequest1$zodSchema),
  z.lazy(() => PostTextMarkdownToPdfBadRequestMarkdown$zodSchema),
  z.lazy(() => PostTextMarkdownToPdfBadRequest2$zodSchema),
  z.lazy(() => PostTextMarkdownToPdfBadRequest3$zodSchema),
  z.lazy(() => Html$zodSchema),
  z.lazy(() => PostTextMarkdownToPdfBadRequest4$zodSchema),
  z.lazy(() => PostTextMarkdownToPdfBadRequest5$zodSchema),
]).describe("请求参数不合法，或者 Markdown 内容包含当前不允许的内容。");

export type PostTextMarkdownToPdfResponseResult =
  | Uint8Array
  | string
  | PostTextMarkdownToPdfBadRequest1
  | PostTextMarkdownToPdfBadRequestMarkdown
  | PostTextMarkdownToPdfBadRequest2
  | PostTextMarkdownToPdfBadRequest3
  | Html
  | PostTextMarkdownToPdfBadRequest4
  | PostTextMarkdownToPdfBadRequest5
  | RequestEntityTooLargeMarkdown
  | RequestEntityTooLarge
  | PostTextMarkdownToPdfInternalServerErrorResponseBody
  | PostTextMarkdownToPdfBadGatewayResponseBody
  | ServiceUnavailable1
  | ServiceUnavailable2
  | PostTextMarkdownToPdfGatewayTimeoutResponseBody;

export const PostTextMarkdownToPdfResponseResult$zodSchema: z.ZodType<
  PostTextMarkdownToPdfResponseResult
> = z.union([
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.union([
    z.lazy(() => PostTextMarkdownToPdfBadRequest1$zodSchema),
    z.lazy(() => PostTextMarkdownToPdfBadRequestMarkdown$zodSchema),
    z.lazy(() => PostTextMarkdownToPdfBadRequest2$zodSchema),
    z.lazy(() => PostTextMarkdownToPdfBadRequest3$zodSchema),
    z.lazy(() => Html$zodSchema),
    z.lazy(() => PostTextMarkdownToPdfBadRequest4$zodSchema),
    z.lazy(() => PostTextMarkdownToPdfBadRequest5$zodSchema),
  ]),
  z.union([
    z.lazy(() => RequestEntityTooLargeMarkdown$zodSchema),
    z.lazy(() => RequestEntityTooLarge$zodSchema),
  ]),
  z.lazy(() => PostTextMarkdownToPdfInternalServerErrorResponseBody$zodSchema),
  z.lazy(() => PostTextMarkdownToPdfBadGatewayResponseBody$zodSchema),
  z.union([
    z.lazy(() => ServiceUnavailable1$zodSchema),
    z.lazy(() => ServiceUnavailable2$zodSchema),
  ]),
  z.lazy(() => PostTextMarkdownToPdfGatewayTimeoutResponseBody$zodSchema),
]);

export type PostTextMarkdownToPdfResponse = {
  Headers: { [k: string]: Array<string> };
  Result:
    | Uint8Array
    | string
    | PostTextMarkdownToPdfBadRequest1
    | PostTextMarkdownToPdfBadRequestMarkdown
    | PostTextMarkdownToPdfBadRequest2
    | PostTextMarkdownToPdfBadRequest3
    | Html
    | PostTextMarkdownToPdfBadRequest4
    | PostTextMarkdownToPdfBadRequest5
    | RequestEntityTooLargeMarkdown
    | RequestEntityTooLarge
    | PostTextMarkdownToPdfInternalServerErrorResponseBody
    | PostTextMarkdownToPdfBadGatewayResponseBody
    | ServiceUnavailable1
    | ServiceUnavailable2
    | PostTextMarkdownToPdfGatewayTimeoutResponseBody;
};

export const PostTextMarkdownToPdfResponse$zodSchema: z.ZodType<
  PostTextMarkdownToPdfResponse
> = z.object({
  Headers: z.record(z.string(), z.array(z.string())).default({}),
  Result: z.union([
    z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    z.union([
      z.lazy(() => PostTextMarkdownToPdfBadRequest1$zodSchema),
      z.lazy(() => PostTextMarkdownToPdfBadRequestMarkdown$zodSchema),
      z.lazy(() => PostTextMarkdownToPdfBadRequest2$zodSchema),
      z.lazy(() => PostTextMarkdownToPdfBadRequest3$zodSchema),
      z.lazy(() => Html$zodSchema),
      z.lazy(() => PostTextMarkdownToPdfBadRequest4$zodSchema),
      z.lazy(() => PostTextMarkdownToPdfBadRequest5$zodSchema),
    ]),
    z.union([
      z.lazy(() => RequestEntityTooLargeMarkdown$zodSchema),
      z.lazy(() => RequestEntityTooLarge$zodSchema),
    ]),
    z.lazy(() =>
      PostTextMarkdownToPdfInternalServerErrorResponseBody$zodSchema
    ),
    z.lazy(() => PostTextMarkdownToPdfBadGatewayResponseBody$zodSchema),
    z.union([
      z.lazy(() => ServiceUnavailable1$zodSchema),
      z.lazy(() => ServiceUnavailable2$zodSchema),
    ]),
    z.lazy(() => PostTextMarkdownToPdfGatewayTimeoutResponseBody$zodSchema),
  ]),
});
