/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * 排序方式
 */
export const Sort = {
  Relevance: "relevance",
  Date: "date",
} as const;
/**
 * 排序方式
 */
export type Sort = ClosedEnum<typeof Sort>;

export const Sort$zodSchema = z.enum([
  "relevance",
  "date",
]).describe("排序方式");

/**
 * 时间范围过滤
 */
export const TimeRange = {
  Day: "day",
  Week: "week",
  Month: "month",
  Year: "year",
} as const;
/**
 * 时间范围过滤
 */
export type TimeRange = ClosedEnum<typeof TimeRange>;

export const TimeRange$zodSchema = z.enum([
  "day",
  "week",
  "month",
  "year",
]).describe("时间范围过滤");

export type PostSearchAggregateRequest = {
  query: string;
  site?: string | undefined;
  filetype?: string | undefined;
  fetch_full?: boolean | undefined;
  sort?: Sort | undefined;
  time_range?: TimeRange | undefined;
};

export const PostSearchAggregateRequest$zodSchema: z.ZodType<
  PostSearchAggregateRequest
> = z.object({
  fetch_full: z.boolean().default(false).describe(
    "是否获取页面完整正文（会影响响应时间）",
  ),
  filetype: z.string().optional().describe(
    "限制文件类型，不需要 `filetype:` 前缀。支持 pdf、doc、docx、ppt、pptx、xls、xlsx、txt 等",
  ),
  query: z.string().describe("搜索查询关键词，支持中英文"),
  site: z.string().optional().describe("限制搜索特定网站，不需要 `site:` 前缀"),
  sort: Sort$zodSchema.default("relevance").describe("排序方式"),
  time_range: TimeRange$zodSchema.optional().describe("时间范围过滤"),
});

/**
 * 服务器内部错误
 */
export type PostSearchAggregateInternalServerErrorResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostSearchAggregateInternalServerErrorResponseBody$zodSchema:
  z.ZodType<PostSearchAggregateInternalServerErrorResponseBody> = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }).describe("服务器内部错误");

/**
 * 请求过于频繁
 */
export type PostSearchAggregateTooManyRequestsResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostSearchAggregateTooManyRequestsResponseBody$zodSchema:
  z.ZodType<PostSearchAggregateTooManyRequestsResponseBody> = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }).describe("请求过于频繁");

/**
 * 未授权
 */
export type PostSearchAggregateUnauthorizedResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostSearchAggregateUnauthorizedResponseBody$zodSchema: z.ZodType<
  PostSearchAggregateUnauthorizedResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("未授权");

/**
 * 请求参数错误
 */
export type PostSearchAggregateBadRequestResponseBody = {
  code?: string | undefined;
  message?: string | undefined;
};

export const PostSearchAggregateBadRequestResponseBody$zodSchema: z.ZodType<
  PostSearchAggregateBadRequestResponseBody
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
}).describe("请求参数错误");

export type PostSearchAggregateResult = {
  title?: string | undefined;
  url?: string | undefined;
  snippet?: string | undefined;
  domain?: string | undefined;
  source?: string | undefined;
  position?: number | undefined;
  score?: number | undefined;
  publish_time?: string | undefined;
};

export const PostSearchAggregateResult$zodSchema: z.ZodType<
  PostSearchAggregateResult
> = z.object({
  domain: z.string().optional().describe("来源域名"),
  position: z.int().optional().describe("原始排名位置"),
  publish_time: z.iso.datetime({ offset: true }).optional().describe(
    "发布时间（ISO 8601 格式）",
  ),
  score: z.number().optional().describe("综合得分（0-1，已经过排序）"),
  snippet: z.string().optional().describe("结果摘要/描述"),
  source: z.string().optional(),
  title: z.string().optional().describe("结果标题"),
  url: z.string().optional().describe("结果链接"),
});

export type PostSearchAggregateSource = {
  name?: string | undefined;
  status?: string | undefined;
  result_count?: number | undefined;
  elapsed_ms?: number | undefined;
  first_result_host?: string | undefined;
};

export const PostSearchAggregateSource$zodSchema: z.ZodType<
  PostSearchAggregateSource
> = z.object({
  elapsed_ms: z.int().optional().describe("该搜索引擎的耗时（毫秒）"),
  first_result_host: z.string().optional().describe("该搜索源首条结果的域名"),
  name: z.string().optional().describe("搜索引擎版本"),
  result_count: z.int().optional().describe("该搜索引擎返回的结果数"),
  status: z.string().optional().describe("本次搜索引擎调用状态"),
});

/**
 * 服务端实际生效的请求参数回显
 */
export type RequestParams = {
  query?: string | undefined;
  limit?: number | undefined;
  page?: number | undefined;
  timeout_ms?: number | undefined;
  sort?: string | undefined;
};

export const RequestParams$zodSchema: z.ZodType<RequestParams> = z.object({
  limit: z.int().optional().describe("实际生效的返回条数"),
  page: z.int().optional().describe("实际生效的页码"),
  query: z.string().optional().describe("实际执行的搜索词"),
  sort: z.string().optional().describe("实际生效的排序方式"),
  timeout_ms: z.int().optional().describe("实际生效的超时时间（毫秒）"),
}).describe("服务端实际生效的请求参数回显");

/**
 * 本次请求的处理元数据
 */
export type Metadata = {
  request_params?: RequestParams | undefined;
  dedupe_removed?: number | undefined;
  rerank_applied?: boolean | undefined;
  content_fetched?: number | undefined;
};

export const Metadata$zodSchema: z.ZodType<Metadata> = z.object({
  content_fetched: z.int().optional().describe("额外抓取正文的结果数"),
  dedupe_removed: z.int().optional().describe("去重后移除的结果数"),
  request_params: z.lazy(() => RequestParams$zodSchema).optional().describe(
    "服务端实际生效的请求参数回显",
  ),
  rerank_applied: z.boolean().optional().describe("是否执行了排序重排"),
}).describe("本次请求的处理元数据");

/**
 * 搜索成功，返回经过智能排序的搜索结果、本次命中的搜索源信息和请求元数据
 */
export type PostSearchAggregateResponseBody = {
  query?: string | undefined;
  total_results?: number | undefined;
  results?: Array<PostSearchAggregateResult> | undefined;
  sources?: Array<PostSearchAggregateSource> | undefined;
  process_time_ms?: number | undefined;
  metadata?: Metadata | undefined;
};

export const PostSearchAggregateResponseBody$zodSchema: z.ZodType<
  PostSearchAggregateResponseBody
> = z.object({
  metadata: z.lazy(() => Metadata$zodSchema).optional().describe(
    "本次请求的处理元数据",
  ),
  process_time_ms: z.int().optional().describe("本次请求总耗时（毫秒）"),
  query: z.string().optional().describe("执行的搜索查询"),
  results: z.array(z.lazy(() => PostSearchAggregateResult$zodSchema)).optional()
    .describe("搜索结果列表"),
  sources: z.array(z.lazy(() => PostSearchAggregateSource$zodSchema)).optional()
    .describe("本次请求实际命中的搜索引擎信息"),
  total_results: z.int().optional().describe("返回的搜索结果总数"),
}).describe(
  "搜索成功，返回经过智能排序的搜索结果、本次命中的搜索源信息和请求元数据",
);

export type PostSearchAggregateResponse =
  | PostSearchAggregateResponseBody
  | PostSearchAggregateBadRequestResponseBody
  | PostSearchAggregateUnauthorizedResponseBody
  | PostSearchAggregateTooManyRequestsResponseBody
  | PostSearchAggregateInternalServerErrorResponseBody;

export const PostSearchAggregateResponse$zodSchema: z.ZodType<
  PostSearchAggregateResponse
> = z.union([
  z.lazy(() => PostSearchAggregateResponseBody$zodSchema),
  z.lazy(() => PostSearchAggregateBadRequestResponseBody$zodSchema),
  z.lazy(() => PostSearchAggregateUnauthorizedResponseBody$zodSchema),
  z.lazy(() => PostSearchAggregateTooManyRequestsResponseBody$zodSchema),
  z.lazy(() => PostSearchAggregateInternalServerErrorResponseBody$zodSchema),
]);
